{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "/users/hannahgz/revcomp_experiments",
    "dependencies": [
      "ipython==7.4.0",
      "Keras==2.2.4",
      "keras-genomics==0.1.0.0",
      "numpy==1.16.2",
      "sacred==0.7.5",
      "scipy==1.2.1",
      "seqdataloader==0.126",
      "tensorflow-gpu==1.14.0"
    ],
    "mainfile": null,
    "name": "Siamese Model",
    "repositories": [],
    "sources": []
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"<ipython-input-13-622c7bef24c4>\", line 78, in main\n    validation_data = keras_valid_batch_generator)\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py\", line 91, in wrapper\n    return func(*args, **kwargs)\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/keras/engine/training.py\", line 1418, in fit_generator\n    initial_epoch=initial_epoch)\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/keras/engine/training_generator.py\", line 217, in fit_generator\n    class_weight=class_weight)\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/keras/engine/training.py\", line 1217, in train_on_batch\n    outputs = self.train_function(ins)\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py\", line 2715, in __call__\n    return self._call(inputs)\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py\", line 2675, in _call\n    fetched = self._callable_fn(*array_vals)\n",
    "  File \"/users/hannahgz/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\", line 1458, in __call__\n    run_metadata_ptr)\n",
    "tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.\n  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n\t [[{{node sequential_1/conv1d_1/convolution}}]]\n\t [[loss/mul/_123]]\n  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n\t [[{{node sequential_1/conv1d_1/convolution}}]]\n0 successful operations.\n0 derived errors ignored.\n"
  ],
  "heartbeat": "2019-07-30T16:08:34.739602",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz",
    "gpus": {
      "driver_version": "418.56",
      "gpus": [
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        },
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        },
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        },
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        },
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        },
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        },
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        },
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12212
        }
      ]
    },
    "hostname": "nandi.stanford.edu",
    "os": [
      "Linux",
      "Linux-4.4.0-154-generic-x86_64-with-debian-stretch-sid"
    ],
    "python_version": "3.7.3"
  },
  "meta": {
    "command": "main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-07-30T16:08:28.867358",
  "status": "FAILED",
  "stop_time": "2019-07-30T16:08:34.747659"
}